### ISSUE TITLE
Missing icons in some software

### ISSUE THREAD

**Issue by paulpopus** [daniruiz/flat-remix#137]
Not all icons present in a default icon pack are present in this one and some applications break as a result.

Here is a screenshot of the Grub Customizer interface with this icon pack
![Screenshot from 2019-12-03 17-55-42](https://user-images.githubusercontent.com/35137243/70076309-6d69a680-15f6-11ea-925b-f4a757abf0b7.png)
Here is with Humanity-dark
![Screenshot from 2019-12-03 17-56-52](https://user-images.githubusercontent.com/35137243/70076347-81150d00-15f6-11ea-9698-2ceeadf8eb8a.png)

Only found it in grub-customizer so far.
Thanks for your work, let me know if I can help any way.

**Comment by daniruiz** [comment]
I think you didn't properly extract the compressed file. Flat Remix already supports all of the icons that grub customizer uses. When you extract the file ensure it extracts correctly all the symlink files, otherwise you won't be able to use most of the icons.
![image](https://user-images.githubusercontent.com/12565871/70168603-7e371c80-16c9-11ea-868f-17c949eba210.png)
