### ISSUE TITLE
Missing Icon for Xed text editor

### ISSUE THREAD

**Issue by Everest10** [daniruiz/flat-remix#170]
There is no appropriate or missing icon for Xed text editor.

Screenshot below 

![xed](https://user-images.githubusercontent.com/7228207/114807397-b5691380-9d7c-11eb-8793-e1c3934586f1.png)

**Comment by R-a-l-f** [comment]
I confirm that an icon for xed and other editors, at least pluma and medit, too, is missing, at least for 20210322. Issues with 20210414 are described at https://aur.archlinux.org/packages/flat-remix/#comment-801989. I will not reinstall 20210414, to check the editor icon issue. Since the maintainer of the PKGBUILD is upstream, too, I refrain from opening a new issue.

**Comment by daniruiz** [comment]
Sorry but the idea is to use the default text-editor icon for the default text-editor app of the DE, so it makes sense to me to have that generic icon, rather than maintaining different ones for each app.
It's easier to maintain too
