### ISSUE TITLE
All yellow icons are black on yellow ?

### ISSUE THREAD

**Issue by vlycop** [daniruiz/flat-remix#192]
Hello :)
I've try from here, and multiple other source, but it look like all 3 version of the yellow icons set are yellow and back instead of yellow and white ?

I'm thinking the base pack should be clear, and that the "dark" version should be black ? Is this a bug ?
The teaser picture does show white on yellow but maybe it wasn't good and you changed it since ?

Thank you

**Comment by daniruiz** [comment]
Yes, it was changed to black over yellow as otherwise was less visible. Also, all my themes in yellow variant use black text with the highlighted color (otherwise it was completely unreadable), so it made more sense to change the icons too.

The screenshots are outdated, that's why they still show the white color
