### ISSUE TITLE
suggestion: use "C" instead of "X" on LibreOffice Calc

### ISSUE THREAD

**Issue by MingcongBai** [daniruiz/Flat-Remix#33]
I get it, it's an equivalent/alternative to Microsoft Excel, but it seems quite odd to just include an Excel icon embedded in a LibreOffice green icon for LibreOffice Calc.

**Comment by daniruiz** [comment]
Well... After trying many times to edit office icons I wasn't happy with it at all. For example the calc icon with a C locked a bit weird. So finally I've removed all the letters from the icons and I think they still look great. What do you think?
P.S. I know it's been a while since you wrote this but I've been really busy and  as I've said every time I tried to modify them I wasn't happy with the result.

**Comment by MingcongBai** [comment]
Yeah they certainly do still... Just thought that having an "X" there was quite weird. Good work.
