### ISSUE TITLE
Icon Request: hardinfo

### ISSUE THREAD

**Issue by zencubic** [daniruiz/Flat-Remix#43]
It would be very nice if you add an icon for the package "hardinfo"
Links:
[https://help.ubuntu.com/community/HardInfo](https://help.ubuntu.com/community/HardInfo)
[https://github.com/lpereira/hardinfo/](https://github.com/lpereira/hardinfo/)

**Comment by daniruiz** [comment]
Hardinfo already has an icon. The problem is that it uses the icon /usr/share/hardinfo/pixmaps/logo.png instead of just hardinfo. To change it you have to go to /usr/share/applications and open the hardinfo dektop file as superuser with a text editor. Then change Icon=/usr/share/hardinfo/pixmaps/logo.png to Icon=hardinfo
