### ISSUE TITLE
Where authors?

### ISSUE THREAD

**Issue by varlesh** [daniruiz/flat-remix#65]
Copy > Paste it's very cool... but 
You use my icons on your theme and i'm not found own name on CREDITS?

> Some icons are based on:
> Papirus https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

Not based - you not change anything!!!
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/AUTHORS 

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/LICENSE

- License and copyright notice
- State changes
- Disclose source
- Same license

**Comment by daniruiz** [comment]
First of all, I'm really sorry if this has affected your project in any way. Of course, it wasn't my intention.
But I think it could be said in other tone.

It is true all the symbolic icons are taken from Papirus theme, but it isn't just a "copy paste" job, there is also some work on resizing and adjusting them for a better fit with the folder scheme and icon sizes this theme uses, so it can be perfectly said "based on". Anyway I will add the Authors file specifying all of them.

Speaking about the app icons, my intention was to use Papirus app icons as a temporal fallback theme, due to its similarity, and I would later replace all of them with my own designs. But I've been busy with exams and other projects. In any case all the main icons are mine and not from Papirus.

**Comment by varlesh** [comment]
> Speaking about the app icons, my intention was to use Papirus app icons as a temporal fallback theme

Also status, actions and more thousand Papirus icons...

Maybe you don't know about **inherits** option on index theme?
Ok, please read:
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

Now you use Papirus icons on your theme (with resize, of course)
It's my work, my style, stroke, shadows, colors and a lot of time spent. 

I'm not going to argue with you!
You want are violating copyright?

**Comment by varlesh** [comment]
If you use someone else's work, you must write about authors!
