### ISSUE TITLE
add icon for idea | idea-ultimate

### ISSUE THREAD

**Issue by JoseGuadalupeVidalAnaya** [daniruiz/flat-remix#84]
`[Desktop Entry]
Version=1.0
Type=Application
Name=Idea Ultimate
Icon=idea
Exec="/home/jose/.local/share/umake/ide/idea-ultimate/bin/idea.sh" %f
Comment=IntelliJ IDEA (UDTC)
Categories=Development;IDE;
Terminal=false
`

![idea](https://user-images.githubusercontent.com/24641773/47532389-da4c3200-d875-11e8-89bc-bdbd61cc1b74.png)

**Comment by daniruiz** [comment]
Previous Flat-Remix versions included idea icons but I removed them because:

1. They are hardcoded so you would need to modify the .desktop file manually for them to work.
1. The original icons match perfectly with flat remix theme.

So there is no point of adding a new icon that nobody is going to use and even looks pretty much like the original one.
